# Generated by Django 2.2.6 on 2019-10-28 09:49

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20191028_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='created_date',
        ),
        migrations.AddField(
            model_name='quote',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Entry', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
