# Generated by Django 2.2.6 on 2019-10-28 11:09

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20191028_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.AlterModelManagers(
            name='quote',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='is_removed',
        ),
        migrations.AddField(
            model_name='quote',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
